### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by xiaoxiaozhangx** [athanasiospap/Pulse#1]
HeartRateManager.swift  when capture camera ! fatal error! when build the code!

**Comment by thanospapazoglou** [comment]
Can you give me some more information about the fatal error? 
Because, I've just run it in three devices (real, not simulator) and it's working as usual.

(Sorry for the delayed answer, I was on vacay 🏖)

**Comment by Gargo** [comment]
@athanasiospap maybe he means when you install the app - it requests camera permissions. When you deny access to a camera and relaunch the app - it will always fail because of "unavailable camera" exception. When you catch this exception you just throw `fatalError`
